import { ArrowLeft, Download, Save, Send } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import AdminLayout from '../../components/AdminLayout';
import LoadingState from '../../components/LoadingState';
import { api } from '../../services/api';
import type { MetaResponse, OfferInput, OfferStatus } from '../../types';
import { computeDiscount, formatBRL } from '../../utils/money';

const blank: OfferInput = { title:'',description:'',image_url:'',original_url:'',brand:'',keywords:[],store_id:'',category_id:'',old_price:'',current_price:'',status:'DRAFT',featured:false };

export default function AdminOfferEditorPage() {
  const { id }=useParams(); const numericId=id?Number(id):null; const navigate=useNavigate();
  const [form,setForm]=useState<OfferInput>(blank); const [meta,setMeta]=useState<MetaResponse>({categories:[],stores:[]}); const [loading,setLoading]=useState(Boolean(numericId)); const [saving,setSaving]=useState(false); const [importing,setImporting]=useState(false); const [message,setMessage]=useState('');
  useEffect(()=>{ api.adminTaxonomy().then(setMeta).catch(()=>{}); if(numericId){ const p=new URLSearchParams({page:'1',limit:'1',id:String(numericId)}); api.adminOffers(p).then(r=>{const o=r.items[0]; if(!o) throw new Error('Oferta não encontrada.'); setForm({title:o.title,description:o.description||'',image_url:o.image_url||'',original_url:o.original_url||'',brand:o.brand||'',keywords:o.keywords||[],store_id:o.store_id,category_id:o.category_id,old_price:o.old_price?.toString()||'',current_price:o.current_price.toString(),status:o.status,featured:o.featured});}).catch(e=>setMessage(e.message)).finally(()=>setLoading(false)); } },[numericId]);
  const discount=useMemo(()=>computeDiscount(Number(String(form.old_price).replace(',','.'))||null,Number(String(form.current_price).replace(',','.'))||null),[form.old_price,form.current_price]);
  function patch<K extends keyof OfferInput>(key:K,value:OfferInput[K]){setForm(f=>({...f,[key]:value}));}
  async function importUrl(){ if(!form.original_url.trim()) return setMessage('Cole o link do produto primeiro.'); setImporting(true);setMessage('');try{const r=await api.importOffer(form.original_url.trim()); setForm(f=>({...f,title:r.title||f.title,description:r.description||f.description,image_url:r.image_url||f.image_url,brand:r.brand||f.brand,old_price:r.old_price!=null?String(r.old_price):f.old_price,current_price:r.current_price!=null?String(r.current_price):f.current_price,store_id:r.store_id||f.store_id,category_id:r.category_id||f.category_id,original_url:r.original_url||f.original_url})); setMessage(r.warning||'Dados importados. Revise antes de salvar.');}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível importar automaticamente esta oferta. Preencha os dados manualmente.');}finally{setImporting(false);} }
  async function save(statusOverride?:OfferStatus){setSaving(true);setMessage('');try{const payload={...form,status:statusOverride||form.status}; if(numericId) await api.updateOffer(numericId,payload); else await api.createOffer(payload); navigate('/admin/ofertas');}catch(e){setMessage(e instanceof Error?e.message:'Erro ao salvar.');}finally{setSaving(false);}}
  if(loading) return <AdminLayout title="Oferta"><LoadingState/></AdminLayout>;
  return <AdminLayout title={numericId?'Editar oferta':'Nova oferta'} subtitle="Importe um link, revise os dados e só então publique" actions={<Link className="secondary-button compact" to="/admin/ofertas"><ArrowLeft size={16}/> Voltar</Link>}>
    <form className="offer-editor" onSubmit={e=>{e.preventDefault();void save();}}>
      <section className="admin-card import-box"><div><label>Link do produto<input value={form.original_url} onChange={e=>patch('original_url',e.target.value)} placeholder="https://..." required/></label><small>A importação acontece no backend. Se o site bloquear automação, o cadastro manual continua disponível.</small></div><button type="button" className="secondary-button" onClick={importUrl} disabled={importing}><Download size={17}/>{importing?'Importando…':'IMPORTAR PRODUTO'}</button></section>
      {message?<div className="info-banner">{message}</div>:null}
      <div className="editor-grid"><section className="admin-card editor-fields"><h2>Dados da oferta</h2><label>Título<input value={form.title} onChange={e=>patch('title',e.target.value)} required maxLength={180}/></label><div className="two-cols"><label>Loja<select value={form.store_id} onChange={e=>patch('store_id',e.target.value?Number(e.target.value):'')} required><option value="">Selecione</option>{meta.stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Categoria<select value={form.category_id} onChange={e=>patch('category_id',e.target.value?Number(e.target.value):'')} required><option value="">Selecione</option>{meta.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><div className="two-cols"><label>Marca<input value={form.brand} onChange={e=>patch('brand',e.target.value)} maxLength={100}/></label><label>Imagem (URL)<input value={form.image_url} onChange={e=>patch('image_url',e.target.value)} placeholder="https://..."/></label></div><div className="two-cols"><label>Preço anterior<input inputMode="decimal" value={form.old_price} onChange={e=>patch('old_price',e.target.value)} placeholder="699,90"/></label><label>Preço atual<input inputMode="decimal" value={form.current_price} onChange={e=>patch('current_price',e.target.value)} placeholder="449,90" required/></label></div><label>Descrição<textarea rows={6} value={form.description} onChange={e=>patch('description',e.target.value)} maxLength={5000}/></label><label>Palavras-chave <small>(separe por vírgulas)</small><input value={form.keywords.join(', ')} onChange={e=>patch('keywords',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/></label><div className="two-cols"><label>Status<select value={form.status} onChange={e=>patch('status',e.target.value as OfferStatus)}><option>DRAFT</option><option>ACTIVE</option><option>INACTIVE</option><option>EXPIRED</option></select></label><label className="check-card"><input type="checkbox" checked={form.featured} onChange={e=>patch('featured',e.target.checked)}/><span>Marcar como destaque</span></label></div></section>
      <aside className="admin-card preview-card"><h2>Preview da oferta</h2><div className="preview-image">{form.image_url?<img src={form.image_url} alt=""/>:<span>Imagem do produto</span>}{discount?<b>{discount}% OFF</b>:null}</div><small>{meta.stores.find(s=>s.id===form.store_id)?.name||'Loja'}</small><h3>{form.title||'Título do produto'}</h3>{Number(String(form.old_price).replace(',','.'))>Number(String(form.current_price).replace(',','.'))?<s>{formatBRL(Number(String(form.old_price).replace(',','.')))}</s>:null}<strong>{form.current_price?formatBRL(Number(String(form.current_price).replace(',','.'))):'R$ 0,00'}</strong><p>{form.description||'A descrição aparecerá aqui.'}</p></aside></div>
      <div className="editor-submit"><button type="button" className="secondary-button" disabled={saving} onClick={()=>void save('DRAFT')}><Save size={17}/> SALVAR RASCUNHO</button><button type="button" className="primary-button" disabled={saving} onClick={()=>void save('ACTIVE')}><Send size={17}/> PUBLICAR</button></div>
    </form>
  </AdminLayout>;
}
