import { Pencil, Plus, Trash2 } from 'lucide-react';
import { FormEvent, useEffect, useState } from 'react';
import AdminLayout from '../../components/AdminLayout';
import LoadingState from '../../components/LoadingState';
import { api } from '../../services/api';
import type { MetaResponse } from '../../types';

export default function AdminTaxonomyPage(){
 const [meta,setMeta]=useState<MetaResponse|null>(null); const [cat,setCat]=useState(''); const [store,setStore]=useState({name:'',domain:'',site_url:'',logo_url:''}); const [error,setError]=useState('');
 async function load(){try{setMeta(await api.adminTaxonomy())}catch(e){setError(e instanceof Error?e.message:'Erro')}} useEffect(()=>{void load()},[]);
 async function addCat(e:FormEvent){e.preventDefault();try{await api.createCategory(cat);setCat('');await load()}catch(e){alert(e instanceof Error?e.message:'Erro')}}
 async function addStore(e:FormEvent){e.preventDefault();try{await api.createStore(store);setStore({name:'',domain:'',site_url:'',logo_url:''});await load()}catch(e){alert(e instanceof Error?e.message:'Erro')}}
 async function editCat(id:number,name:string,active:boolean){const n=prompt('Nome da categoria',name);if(n===null)return;await api.updateCategory(id,{name:n,active});await load()}
 async function toggleCat(id:number,active:boolean){await api.updateCategory(id,{active:!active});await load()}
 async function deleteCat(id:number){if(!confirm('Excluir esta categoria? A exclusão será bloqueada se houver ofertas vinculadas.'))return;try{await api.deleteCategory(id);await load()}catch(e){alert(e instanceof Error?e.message:'Não foi possível excluir.')}}
 async function editStore(id:number,s:{name:string;domain:string|null;site_url:string|null;logo_url:string|null;active:boolean}){const name=prompt('Nome da loja',s.name);if(name===null)return;const domain=prompt('Domínio (ex.: exemplo.com.br)',s.domain||'');if(domain===null)return;await api.updateStore(id,{name,domain,site_url:s.site_url,logo_url:s.logo_url,active:s.active});await load()}
 async function toggleStore(id:number,active:boolean){await api.updateStore(id,{active:!active});await load()}
 async function deleteStore(id:number){if(!confirm('Excluir esta loja? A exclusão será bloqueada se houver ofertas vinculadas.'))return;try{await api.deleteStore(id);await load()}catch(e){alert(e instanceof Error?e.message:'Não foi possível excluir.')}}
 return <AdminLayout title="Categorias e lojas" subtitle="Cadastros usados nas ofertas">{error?<div className="error-banner">{error}</div>:null}{!meta?<LoadingState/>:<div className="taxonomy-grid"><section className="admin-card"><h2>Categorias</h2><form className="inline-create" onSubmit={addCat}><input value={cat} onChange={e=>setCat(e.target.value)} placeholder="Nova categoria" required/><button><Plus size={16}/>Adicionar</button></form><div className="taxonomy-list">{meta.categories.map(c=><div key={c.id}><div><strong>{c.name}</strong><small>{c.slug}</small></div><span className={c.active?'active-dot':'inactive-dot'}>{c.active?'Ativa':'Inativa'}</span><button onClick={()=>editCat(c.id,c.name,c.active)}><Pencil size={15}/></button><button onClick={()=>toggleCat(c.id,c.active)}>{c.active?'Desativar':'Ativar'}</button><button className="danger" onClick={()=>deleteCat(c.id)}><Trash2 size={15}/></button></div>)}</div></section><section className="admin-card"><h2>Lojas</h2><form className="stack-create" onSubmit={addStore}><input value={store.name} onChange={e=>setStore({...store,name:e.target.value})} placeholder="Nome da loja" required/><input value={store.domain} onChange={e=>setStore({...store,domain:e.target.value})} placeholder="dominio.com.br"/><input value={store.site_url} onChange={e=>setStore({...store,site_url:e.target.value})} placeholder="https://dominio.com.br"/><button><Plus size={16}/>Adicionar loja</button></form><div className="taxonomy-list">{meta.stores.map(s=><div key={s.id}><div><strong>{s.name}</strong><small>{s.domain||'Sem domínio'}</small></div><span className={s.active?'active-dot':'inactive-dot'}>{s.active?'Ativa':'Inativa'}</span><button onClick={()=>editStore(s.id,s)}><Pencil size={15}/></button><button onClick={()=>toggleStore(s.id,s.active)}>{s.active?'Desativar':'Ativar'}</button><button className="danger" onClick={()=>deleteStore(s.id)}><Trash2 size={15}/></button></div>)}</div></section></div>}</AdminLayout>
}
